<a href="https://colab.research.google.com/github/AnjuHaliya/NNDL/blob/main/Assingnment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import Necessary Modules
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [6]:
# Read the dataset
data = pd.read_excel("/slr08 (2) (1).xlsx")
print(data.shape)
data.head()

(30, 2)

       X      Y
0   75.1  577.8
1   74.3  577.0
2   88.7  570.9
3  114.6  578.6
4   98.5  572.4

In [7]:
# Data Normalization
maxX = np.max(data['X'])
minX = np.min(data['X'])
maxY = np.max(data['Y'])
minY = np.min(data['Y'])

data['X'] = (data['X'] - minX) / (maxX - minX)
data['Y'] = (data['Y'] - minY) / (maxY - minY)

In [8]:
# Splitting Data
x = data['X']
y = data['Y']
trainX, testX, trainY, testY = train_test_split(x, y, test_size=0.1, random_state=101)

In [9]:
# Model Training

#Initialization
m = np.random.uniform(-50, 50)
c = np.random.uniform(-50, 50)
eta = 0.5
epochs = 500

# Loop for epochs
for _ in range(epochs):
    
    # Calculating Grad M
    gradM = -sum([(trainY.iloc[i] - m * trainX.iloc[i] - c) * trainX.iloc[i] for i in range(trainX.shape[0])])
    gradM /= trainX.shape[0]
    
    # Calculating Grad C
    gradC = -sum([(trainY.iloc[i] - m * trainX.iloc[i] - c) for i in range(trainX.shape[0])])
    gradC /= trainX.shape[0]
    
    # Updating m and c values
    c += - eta * gradC
    m += - eta * gradM

# Print model parameters after training
print(f'm = {m}\nc = {c}')

m = -0.15335158503885105
c = 0.6967024859557944

In [10]:
# Calculating Predictions
train_pred = [m * trainX.iloc[i] + c for i in range(trainX.shape[0])]
test_pred = [m * testX.iloc[i] + c for i in range(testX.shape[0])]

# Denormalization of Output Values
train_pred = [i * (maxY - minY) + minY for i in train_pred]
test_pred = [i * (maxY - minY) + minY for i in test_pred]
trainY = [i * (maxY - minY) + minY for i in trainY]
testY = [i * (maxY - minY) + minY for i in testY]

# Training Error Calculation
training_MAE = sum([abs(train_pred[i] - trainY[i]) for i in range(len(trainY))]) / len(trainY)
training_MSE = sum([(train_pred[i] - trainY[i]) ** 2 for i in range(len(trainY))]) / len(trainY)
training_RMSE = training_MSE ** 0.5
print('Training Error :')
print(f'MAE : {training_MAE}')
print(f'MSE : {training_MSE}')
print(f'RMSE : {training_RMSE}')

# Testing Error Calculation
testing_MAE = sum([abs(test_pred[i] - testY[i]) for i in range(len(testY))]) / len(testY)
testing_MSE = sum([(test_pred[i] - testY[i]) ** 2 for i in range(len(testY))]) / len(testY)
testing_RMSE = testing_MSE ** 0.5
print('Testing Error :')
print(f'MAE : {testing_MAE}')
print(f'MSE : {testing_MSE}')
print(f'RMSE : {testing_RMSE}')

Training Error :
MAE : 26.70997040141418
MSE : 1532.8193421927253
RMSE : 39.1512367900776
Testing Error :
MAE : 19.052533001681127
MSE : 532.4581526949354
RMSE : 23.07505477122287

In [11]:
# Checking predicted training values
pd.DataFrame({'Actual' : trainY, 'Predicted':train_pred})

    Actual   Predicted
0    508.6  504.753985
1    570.9  514.377169
2    510.0  517.478479
3    513.4  520.078107
4    506.3  524.638857
5    512.8  520.214929
6    504.3  516.383899
7    496.4  521.172687
8    578.6  502.564825
9    577.0  520.944649
10   510.9  506.760715
11   502.8  521.172687
12   506.4  509.497166
13   411.2  503.750620
14   503.9  521.127079
15   577.8  520.579789
16   512.8  513.966701
17   572.4  509.907633
18   406.7  506.030995
19   510.2  512.416046
20   507.1  513.556234
21   506.2  524.866895
22   522.0  510.135671
23   493.0  508.630623
24   531.7  502.473610
25   510.2  519.302779
26   505.2  502.017535

In [12]:
# Checking predicted testing values
pd.DataFrame({'Actual' : testY, 'Predicted':test_pred})

   Actual   Predicted
0   505.4  514.422776
1   510.8  500.102020
2   563.9  526.463157

In [13]:
# Real Time Prediction
x = float(input('Enter the pressure of liquid nitrogen : '))
x = (x - minX) / (maxX - minX)
prediction = m * x + c
prediction = (prediction * (maxY - minY)) + minY
print('Predicted Weight :', prediction)

Enter the pressure of liquid nitrogen : 115
Predicted Weight : 502.3823950811328